### ISSUE TITLE
Not returning response if request is invalid

### ISSUE THREAD

**Issue by 1aerostorm** [shogowada/json-rpc-2.0#17]
If request is invalid (not object, hasn't required fields, etc.) library just logs it to console and rejects promise:
https://github.com/shogowada/json-rpc-2.0/blob/master/src/server.ts#L94-L97

So user should handle this error by himself, i.e. compose -32700 error response, and return it.

It is better to return such response from the library.

This library: https://www.npmjs.com/package/simple-jsonrpc-js has more accurate JSON-RPC 2.0 implementation, and it includes such logic.

**Comment by shogowada** [comment]
Ah, thanks for the catch 🙂 I'll fix it.

**Comment by shogowada** [comment]
Fixed with https://github.com/shogowada/json-rpc-2.0/commit/a2b6032d1d583e8f1065c873b83b27ee4f35f097

Please install v0.2.16 to receive the fix.

For the parse error, since it didn't have any method to receive JSON as is, I added `receiveJSON` method to the `JSONRPCServer` class. This method takes JSON string instead of parsed JSON like `receive` method does.

If the JSON parse failed, it returns a -32700 error response. If the request could be parsed but was invalid, it returns a -32600 error response per spec.
