### ISSUE TITLE
extended example

### ISSUE THREAD

**Issue by gfijrb** [shogowada/json-rpc-2.0#3]
Hi can you provide more extended describe how to use your library with curl queries and result response examples

**Comment by shogowada** [comment]
Sure.

What do you mean by curl queries, though? It's a JavaScript library. Do you mean to execute curl using command line? E.g. `require("child_process").exec("curl http://localhost")`?

**Comment by shogowada** [comment]
Oh maybe you meant a curl request/response example hitting the server, exposing JSON-RPC API via HTTP?

**Comment by gfijrb** [comment]
> Oh maybe you meant a curl request/response example hitting the server, exposing JSON-RPC API via HTTP?

something like that:
```
curl -X POST -H 'Content-Type: application/json' -d '{"jsonrpc": "2.0", "method": "log", "params": {"message":"davidwalsh"}}' --url 'http://localhost:3000/json-rpc'

// result: {smth: "answer"}
```

**Comment by shogowada** [comment]
Hi, I'm sorry for the late response.

I think [the official JSON-RPC 2.0 spec page](https://www.jsonrpc.org/specification) has plenty of raw JSON examples, and this library isn't specific to HTTP (although it can be used via HTTP), so I think it's better NOT to include the curl example so that the README can focus on how to use this library.

But I just noticed that the README doesn't link to the official spec, so [I linked it](https://github.com/shogowada/json-rpc-2.0/commit/c27737f074227473235e067169aea1948599dc5a). Hopefully this suffices.

Thanks
