### ISSUE TITLE
error response data not available

### ISSUE THREAD

**Issue by okaihc** [shogowada/json-rpc-2.0#7]
Sometimes a JSON-RPC-2.0 server attaches data to an error response. The data is lost after the JSON is run through Client.receiveAndSend. It would be good to have that data be attached to the error object.

**Comment by shogowada** [comment]
Hi, sorry it seems I somehow missed it.

`JSONRPCClient` has `requestAdvanced` method which gives you JSON-RPC response as is, including the error data, but it looks like `JSONRPCServerAndClient` doesn't expose the equivalent method.

Given that, since it exposes `client` as a public member variable, maybe you could do `jsonRPCServerAndClient.client.requestAdvanced`.
